[tasks.DB]
description = "Create DB"
script = ['''
#!/usr/bin/env bash
docker stop postgresql-container || :
docker run --rm -d --name postgresql-container -p 5432:5432 -e POSTGRES_PASSWORD=password postgres
sleep 3
PGPASSWORD=password psql -h localhost -U postgres -d postgres < ulid.sql
PGPASSWORD=password psql -h localhost -U postgres -d postgres < preparation.sql
''']
